## Default values for elasticsearch.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
############################################################################
es:
  enabled: true

image:
  repository: akhilrajmailbox/elasticsearch
  tag: elasticsearch-6.8.0
  # tag: elasticsearch-6.8.0-plugins
  pullPolicy: Always

## Configure basic auth for the deployment; when you are upgrading the helm.
## plese use : enabled: "false" otherwise the credentials will overwrite..
EsAuthAutoCreation:
  enabled: true
  # enable this for authetication
  auth_config: "true"
  # APM Server token
  apmToken: "ARHelmApMTokeN"
  # Kibana Admin user (kibanAdmin) Pass 
  kibanaAdminPass: "ARHelmKibanaAdmiNSecreT"
  # Kibana Readonly user (kibanaUser) Pass 
  kibanaRoUserPass: "ARHelmKibanaRoSecreT"
  # ElasticSearch User (LogAdmin) Pass to push togs to ES Cluster from fluentd / filebeat etc..
  esClientPass: "ARHelmLogPusHSecreT"

cluster_name: "ar-es"


############################################################################
## Enable snapshot configuration for either for AWS, GCP or Azure
EsSnapshot:
  enabled: false
  azureblob:
    enabled: false
    azureSnap: "true"
    account_name: ""
    account_key: ""
  gcs:
    enabled: false
    gcsSnap: "true"
  s3:
    enabled: false
    s3Snap: "true"
    access_key: ""
    secret_key: ""

############################################################################
## enable cronjob deployment for snapshotting specific indices and deleteing old indices
EsSnapshotCronJob:
  enabled: false
  image:
    repository: akhilrajmailbox/elasticsearch
    tag: cron-snapshots
    pullPolicy: Always
  # use 'production' for creating snapshot and delete old snapshots, otherwise it will not snapshot anything but will delete the old indices
  myenv: "production"
  # elasticsearch access with credentials,
  # example : http://kibanAdmin:ARHelmKibanaAdmiNSecreT@10.50.145.35:9200/
  host: "http://kibanAdmin:ARHelmKibanaAdmiNSecreT@34.71.225.186:9200/"
  # indice starting name to create snapshot, deleting old one
  # example : apm- , in here all indices starting with apm- will consider
  snapindices: "apm-"
  # 90 days old indices will get delete
  indicesdeldays: "90"
  # snapshot repository name you created
  # example : development-elasticsearch-storage
  snaprepo: "es_backup"
  # snapshot aged 1 year will get delete from the snapshot repository
  snapdeldays: "365"

############################################################################
## ES Node for cluster (master, data and client will install on same pod)
node:
  enabled: false
  replicaCount: 3
  podDisruptionBudget:
    enabled: false
    minAvailable: 2
    # maxUnavailable: 1
  priorityClassName: ""
  ## system-cluster-critical or system-node-critical
  number_of_master: "1"
  java_opts: "-Xms4G -Xmx4G"

  resources:
    requests:
      memory: "4Gi"
      cpu: 200m
    limits:
      memory: "6Gi"
      cpu: 2

  nodeSelector: {}

  tolerations: []

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: role
              operator: In
              values:
              - node
          topologyKey: "kubernetes.io/hostname"

  service:
    discovery:
      port: 9300
      protocol: TCP
      annotations: {}
    client:
      type: LoadBalancer
      port: 9200
      protocol: TCP
      annotations: {}

  persistence:
    enabled: true
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 50Gi

############################################################################
## ES Master Node
master:
  replicaCount: 3
  podDisruptionBudget:
    enabled: false
    minAvailable: 2
    # maxUnavailable: 1
  priorityClassName: ""
  ## system-cluster-critical or system-node-critical
  number_of_master: "2"
  java_opts: "-Xms1G -Xmx1G"

  resources:
    requests:
      memory: "1Gi"
      cpu: 50m
    limits:
      memory: "2Gi"
      cpu: 1

  nodeSelector: {}

  tolerations: []

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: role
              operator: In
              values:
              - master
          topologyKey: "kubernetes.io/hostname"

  service:
    port: 9300
    protocol: TCP
    annotations: {}

############################################################################
## ES Data Node
data:
  replicaCount: 3
  podDisruptionBudget:
    enabled: false
    minAvailable: 2
    # maxUnavailable: 1
  priorityClassName: ""
  ## system-cluster-critical or system-node-critical
  java_opts: "-Xms4G -Xmx4G"

  resources:
    requests:
      memory: "2Gi"
      cpu: 50m
    limits:
      memory: "5Gi"
      cpu: 1

  nodeSelector: {}

  tolerations: []

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: role
              operator: In
              values:
              - data
          topologyKey: "kubernetes.io/hostname"

  service:
    port: 9300
    protocol: TCP
    annotations: {}

  persistence:
    enabled: true
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 50Gi

############################################################################
## ES Client Node
client:
  replicaCount: 2
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    # maxUnavailable: 1
  priorityClassName: ""
  ## system-cluster-critical or system-node-critical
  java_opts: "-Xms1G -Xmx1G"

  resources:
    requests:
      memory: "1Gi"
      cpu: 50m
    limits:
      memory: "2Gi"
      cpu: 1

  nodeSelector: {}

  tolerations: []

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: role
              operator: In
              values:
              - client
          topologyKey: "kubernetes.io/hostname"

  service:
    type: LoadBalancer
    port: 9200
    protocol: TCP
    annotations: {}

############################################################################
## APM Server Node
apm:
  enabled: true
  # # ElasticSearch Admin Name to connect to ElasticSearch Cluster
  # esAdmin: "kibanAdmin"
  # # ElasticSearch Admin Password to connect to ElasticSearch Cluster
  # esPassword: "ARHelmKibanaAdmiNSecreT"
  # # ElasticSearch URL
  # esUrl: http://es-cluster-es-client.es.svc.cluster.local:9200
  # # APM Secret Token
  # apmToken: "ARHelmApMTokeN"
  image:
    repository: akhilrajmailbox/elasticsearch
    tag: apm-server-6.8.0
    pullPolicy: Always
  replicaCount: 2
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    # maxUnavailable: 1
  priorityClassName: ""
  ## system-cluster-critical or system-node-critical
  resources:
    requests:
      memory: "512Mi"
      cpu: 100m
    limits:
      memory: "1Gi"
      cpu: 1

  nodeSelector: {}

  tolerations: []

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: role
              operator: In
              values:
              - apm
          topologyKey: "kubernetes.io/hostname"

  service:
    type: LoadBalancer
    port: 80
    protocol: TCP
    annotations: {}


############################################################################
## Kibana Server Node
kibana:
  enabled: true
  # # ElasticSearch Admin Name to connect to ElasticSearch Cluster
  # esAdmin: "kibanAdmin"
  # # ElasticSearch Admin Password to connect to ElasticSearch Cluster
  # esPassword: "ARHelmKibanaAdmiNSecreT"
  # # ElasticSearch URL
  # esUrl: http://es-cluster-es-client.es.svc.cluster.local:9200
  image:
    repository: akhilrajmailbox/elasticsearch
    tag: kibana-6.8.0
    pullPolicy: Always
  replicaCount: 1
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    # maxUnavailable: 1
  priorityClassName: ""
  ## system-cluster-critical or system-node-critical
  resources:
    requests:
      memory: "512Mi"
      cpu: 100m
    limits:
      memory: "1Gi"
      cpu: 500m

  nodeSelector: {}

  tolerations: []

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: role
              operator: In
              values:
              - kibana
          topologyKey: "kubernetes.io/hostname"

  service:
    type: LoadBalancer
    port: 80
    protocol: TCP
    annotations: {}