{{ if .Values.apm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}-apm
  labels:
{{ include "labels.standard" . | indent 4 }}
    component: elasticsearch
    role: apm
data:
  apm-server.yml: |-
    apm-server:
        host: 0.0.0.0:8200
        secret_token: "${ELASTIC_APM_SECRET_TOKEN}"
        read_timeout: 45s

    output:
        elasticsearch:
            hosts: "${ELASTICSEARCH_URL}"
            username: "${KIBANA_ADMIN}"
            password: "${ADMIN_PASSWORD}"
{{ end }}