{{ if .Values.EsAuthAutoCreation.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch.fullname" . }}-es-auth-secret
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  {{ if or (.Values.es.enabled) (.Values.node.enabled) }}
  AUTH_CONFIG: {{ .Values.EsAuthAutoCreation.auth_config | b64enc | quote }}
  ELASTIC_APM_SECRET_TOKEN: {{ .Values.EsAuthAutoCreation.apmToken | b64enc | quote }}
  KIBANA_ADMIN_PASSWORD: {{ .Values.EsAuthAutoCreation.kibanaAdminPass | b64enc | quote }}
  KIBANA_RO_PASSWORD: {{ .Values.EsAuthAutoCreation.kibanaRoUserPass | b64enc | quote }}
  PUSHLOG_PASSWORD: {{ .Values.EsAuthAutoCreation.esClientPass | b64enc | quote }}
  {{ end }}
  {{ if and (not .Values.es.enabled) (not .Values.node.enabled) (.Values.apm.enabled) }}
  KIBANA_ADMIN: {{ .Values.apm.esAdmin | b64enc | quote }}
  KIBANA_ADMIN_PASSWORD: {{ .Values.apm.esPassword | b64enc | quote }}
  ELASTICSEARCH_URL: {{ .Values.apm.esUrl | b64enc | quote }}
  ELASTIC_APM_SECRET_TOKEN: {{ .Values.apm.apmToken | b64enc | quote }}
  {{ end }}
  {{ if and (not .Values.es.enabled) (not .Values.node.enabled) (.Values.kibana.enabled) }}
  KIBANA_ADMIN: {{ .Values.kibana.esAdmin | b64enc | quote }}
  KIBANA_ADMIN_PASSWORD: {{ .Values.kibana.esPassword | b64enc | quote }}
  ELASTICSEARCH_URL: {{ .Values.kibana.esUrl | b64enc | quote }}
  {{ end }}
{{ end }}