{{ if and (.Values.es.enabled) (not .Values.node.enabled) }}
{{ if .Values.client.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "elasticsearch.fullname" . }}-client-pdb
  labels:
    {{ include "labels.standard" . | indent 4 }}
    component: elasticsearch
    role: client
spec:
{{- if .Values.client.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.client.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.client.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.client.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
        {{ include "labels.standard" . | indent 4 }}
        component: elasticsearch
        role: client
{{ end }}
{{ end }}