{{ if .Values.EsSnapshot.enabled }}
{{ if or (.Values.es.enabled) (.Values.node.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch.fullname" . }}-es-snapshot-secret
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.EsSnapshot.azureblob.enabled }}
  AZURE_REPOSITORY_CONFIG: {{ .Values.EsSnapshot.azureblob.azureSnap | b64enc | quote }}
  AZURE_REPOSITORY_ACCOUNT_NAME: {{ .Values.EsSnapshot.azureblob.account_name | b64enc | quote }}
  AZURE_REPOSITORY_ACCOUNT_KEY: {{ .Values.EsSnapshot.azureblob.account_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.EsSnapshot.gcs.enabled }}
  GCS_REPOSITORY_CONFIG: {{ .Values.EsSnapshot.gcs.gcsSnap | b64enc | quote }}
  {{- end }}
  {{- if .Values.EsSnapshot.s3.enabled }}
  S3_REPOSITORY_CONFIG: {{ .Values.EsSnapshot.s3.s3Snap | b64enc | quote }}
  S3_ACCESS_KEY: {{ .Values.EsSnapshot.s3.access_key | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.EsSnapshot.s3.secret_key | b64enc | quote }}
  {{- end }}
{{ end }}
{{ end }}
