{{ if .Values.EsSnapshotCronJob.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch.fullname" . }}-es-cronsnap
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  myenv: {{ .Values.EsSnapshotCronJob.myenv | b64enc | quote }}
  host: {{ .Values.EsSnapshotCronJob.host | b64enc | quote }}
  snapindices: {{ .Values.EsSnapshotCronJob.snapindices | b64enc | quote }}
  indicesdeldays: {{ .Values.EsSnapshotCronJob.indicesdeldays | b64enc | quote }}
  snaprepo: {{ .Values.EsSnapshotCronJob.snaprepo | b64enc | quote }}
  snapdeldays: {{ .Values.EsSnapshotCronJob.snapdeldays | b64enc | quote }}
{{ end }}