{{ if .Values.kibana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}-kibana
  labels:
{{ include "labels.standard" . | indent 4 }}
    component: elasticsearch
    role: kibana
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    elasticsearch.url: "${ELASTICSEARCH_URL}"
    elasticsearch.username: "${KIBANA_ADMIN}"
    elasticsearch.password: "${ADMIN_PASSWORD}"
{{ end }}